import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./Context/store";
import Navbar from "@/components/Navbar";
import Chatbot from "@/feature/Chatbot/components/Chatbot";
import { Providers } from "@/lib/providers";
const poppins = Poppins({ subsets: ["latin"], weight:['400','300','600','700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={poppins.className}>
          <AppProvider>
            <div className="">
              <div className="h-full mb-28">
                {children}
              </div>
              <div className="fixed bottom-[90px] right-8 z-50">
                <Chatbot />
              </div>
              <Navbar />
            </div>
          </AppProvider>
        </body>
      </html>
    </Providers>
  );
}
